openapi: 3.0.3
info:
  title: Learning English for sberSalute
  description: Learning English for sberSalute
  version: 1.0.0
servers:
  -   url: http://localhost:8080/
paths:
  /v1/random:
    get:
      parameters:
        -  name: count
           in: header
           description: returned sarray size
           schema:
             type: integer
        -  name: code
           in: header
           description: code word
           schema:
             type: string
        -  name: task-type
           in: header
           description: on of many-many task types
           schema:
             type: string
             enum:
               - ANY
               - PRESENT_SIMPLE
               - PAST_SIMPLE
               - FUTURE_SIMPLE
      description: returns random task of task-type
      responses:
        '200':
          description: OK

          content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      q:
                        description: question
                        type: string
                      a:
                        description: answer
                        type: string
                      variants:
                        description: variants of answers
                        type: array
                        items:
                          type: string
                          description: variant
                      correct:
                        description: number of correct answer
                        type: integer
                    description: task with answer





        '401':
          description: unauthorised




