openapi: 3.0.3
info:
  title: Learning English for sberSalute
  description: Learning English for sberSalute
  version: 1.0.0
servers:
  -   url: http://localhost:8080/
paths:
  /v1/types:
    get:
      parameters:
        - name: code
          in: header
          description: secret
          schema:
            type: string
      description: get all existing folders in tasks folder
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: all task types
                items:
                  type: string
        401:
          description: Unauthorized

  /v1/{task-type}/all:
    get:
      parameters:
        -  name: code
           in: header
           description: code word
           schema:
             type: string
        -  name: task-type
           in: path
           description: on of many-many task types
           schema:
             type: string
      description: returns random task of task-type
      responses:
        '200':
          description: OK

          content:
              application/json:
                schema:
                  type: array
                  description: task with answer
                  items:
                    type: object
                    properties:
                      q:
                        description: question
                        type: string
                      a:
                        description: answer
                        type: string
                      variants:
                        description: variants of answers
                        type: array
                        items:
                          type: string
                          description: variant
                      correct:
                        description: number of correct answer
                        type: integer
        '401':
          description: Unauthorised
  /v1/{task-type}/description:
    get:
      parameters:
        - name: code
          in: header
          description: code word
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        401:
          description: Unauthorised
        400:
          description: no such description file
